insert into public.admins (role, login, password, displayed_name, created, updated) values ('ROLE_ADMIN', 'admin',      '12345678', 'Administrator', timezone('UTC', now()), timezone('UTC', now()));
insert into public.admins (role, login, password, displayed_name, created, updated) values ('ROLE_MODER', 'moderator1', '12345678', 'Moderator1',    timezone('UTC', now()), timezone('UTC', now()));
insert into public.admins (role, login, password, displayed_name, created, updated) values ('ROLE_MODER', 'moderator2', '12345678', 'Moderator2',    timezone('UTC', now()), timezone('UTC', now()));

insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user1',  '12345678', 'Ivan',    'Ivanov',      'MALE',   '1967-11-01', 'ivan.i@gmail.com',      '+375441234567', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user2',  '12345678', 'Petr',    'Petrov',      'MALE',   '1988-10-11', 'dmitriy.b@gmail.com',   '+375442837405', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user3',  '12345678', 'Anna',    'Karenina',    'FEMALE', '1987-08-23', 'maslenitsa@gmail.com',  '+375441234875', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user4',  '12345678', 'Andrey',  'Luchkouski',  'MALE',   '1988-05-10', 'andrey.l@gmail.com',    '+375444637285', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user5',  '12345678', 'Vlad',    'Batsenka',    'MALE',   '1993-06-22', 'vlad.b@gmail.com',      '+375440182647', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user6',  '12345678', 'Dmitriy', 'Bahankou',    'MALE',   '1992-03-18', 'dima.b@gmail.com',      '+375444637285', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user7',  '12345678', 'Natalia', 'Petrova',     'FEMALE', '1978-05-30', 'natusik@gmail.com',     '+375333456789', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user8',  '12345678', 'Oksana',  'Petkitskaya', 'FEMALE', '1985-08-11', 'oksanka@gmail.com',     '+375444637285', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user9',  '12345678', 'Olga',    'Nekrasova',   'FEMALE', '1987-01-20', 'nekrasova.o@gmail.com', '+375293456789', timezone('UTC', now()), timezone('UTC', now()));
insert into public.users (login, password, name, surname, gender, birth_date, email, phone, created, updated) values ('user10', '12345678', 'Aleksey', 'Pobedov',     'MALE',   '1983-04-11', 'pobedoff@gmail.com',    '+375293457586', timezone('UTC', now()), timezone('UTC', now()));

insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (1,  'TYPE_APARTMENT', 'Apartment',                   'Apartment in the middle of a nowhere', 'Belarus, Mogilevskaya, Mogilev, Fatina st. 1-123',            100, 5, 2, 3, true,  true,  false, true,  false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (1,  'TYPE_APARTMENT', 'Just apartment',              'Apartment in the middle of a nowhere', 'Belarus, Mogilevskaya, Mogilev, Fatina st. 1-111',            85,  3, 1, 2, true,  true,  true,  true,  true,  true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (3,  'TYPE_APARTMENT', 'Good choice',                 'Apartment in the middle of a nowhere', 'Belarus, Minskaya, Soligorsk, Zheleznodorozhnaya st. 24-121', 110, 5, 2, 3, true,  true,  true,  true,  false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (4,  'TYPE_APARTMENT', 'Apartment with all you need', 'Apartment in the middle of a nowhere', 'Belarus, Brestskaya, Brest, Fatsina st. 1-123',               75,  2, 2, 1, true,  true,  true,  true,  true,  true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (6,  'TYPE_APARTMENT', 'Some apartment',              'Apartment in the middle of a nowhere', 'Belarus, Minskaya, Minsk, Nikulina st. 8-85',                 60,  2, 1, 2, true,  true,  true,  true,  false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (7,  'TYPE_APARTMENT', 'Apartment #1',                'Apartment in the middle of a nowhere', 'Belarus, Vitebskaya, Vitebsk, Pobedy sq. st. 101-58',         90,  1, 1, 1, false, false, true,  false, false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (9,  'TYPE_ROOM',      'Room in apartment',           'Room in the middle of a nowhere',      'Belarus, Gomelskaya, Gomel, 8 Marta st. st. 12-35',           25,  1, 1, 1, true,  false, true,  false, false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (9,  'TYPE_ROOM',      'Room in apartment',           'Room in the middle of a nowhere',      'Belarus, Gomelskaya, Gomel, 8 Marta st. st. 12-35',           25,  1, 1, 1, true,  false, true,  false, false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (9,  'TYPE_ROOM',      'Room in apartment',           'Room in the middle of a nowhere',      'Belarus, Gomelskaya, Gomel, 8 Marta st. st. 12-35',           25,  1, 1, 1, true,  false, true,  false, false, true, timezone('UTC', now()), timezone('UTC', now()));
insert into public.property (user_id, type, name, description, address, price, guests, rooms, beds, has_kitchen, has_washer, has_tv, has_internet, is_pets_allowed, is_available, created, updated) values (10, 'TYPE_HOUSE',     'Lonely House',                'House in the middle of a nowhere',     'Belarus, Grodnenskaya, Grodno, Nezavisimosti st. 12-35',      25,  1, 1, 1, true,  false, true,  false, false, true, timezone('UTC', now()), timezone('UTC', now()));

insert into public.property_image (property_id, img_url, created, updated) values (1,  'https://image-hosting/images/1/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (1,  'https://image-hosting/images/1/image2.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (1,  'https://image-hosting/images/1/image3.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (2,  'https://image-hosting/images/2/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (2,  'https://image-hosting/images/2/image2.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (3,  'https://image-hosting/images/3/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (4,  'https://image-hosting/images/4/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (5,  'https://image-hosting/images/5/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (6,  'https://image-hosting/images/6/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (7,  'https://image-hosting/images/7/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (8,  'https://image-hosting/images/8/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (9,  'https://image-hosting/images/9/image1.png',  timezone('UTC', now()), timezone('UTC', now()));
insert into public.property_image (property_id, img_url, created, updated) values (10, 'https://image-hosting/images/10/image1.png', timezone('UTC', now()), timezone('UTC', now()));

insert into public.orders (user_id, property_id, total_price, start_date, end_date, created, updated) values (5, 3, 200, '2021-09-20', '2021-09-21', timezone('UTC', now()), timezone('UTC', now()));
insert into public.orders (user_id, property_id, total_price, start_date, end_date, created, updated) values (9, 1, 100, '2021-09-07', '2021-09-07', timezone('UTC', now()), timezone('UTC', now()));

-- review